### PR TITLE
Delete  files from shell script

### LINKED ISSUE #102: Delete the uploaded image after processing
The uploaded images are currently being saved in test_images folder which is mentioned in .gitignore, you are supposed to run a bash script(.sh) to delete the uploaded image after processing.

Hint : Use `rm -f test_images/fileUploadPath` command to delete that image.

### PR DESCRIPTION
**Pull request by abhushanaj**
closes #102 
Deletes all kinds of files for:
- successful submission (images)
- unsuccessful submission (pdf etc. etc.)

Wildcards used: `rm -f test_images/*.*`
Also changed the gitignore files to ignore few system files which were added

### CODE REVIEW

**Review by tanishq9 — COMMENTED** [review]
Can you elaborate a bit more on `/venv` addition in .gitignore. Also : 
1. Now, instead of running setUpDir.sh on runtime, do it using child_process like you have done for removing files, so that we can run server using `node server.js`
2. Make a folder called shell_scripts and add both setUp and deleteDir .sh there.

**Comment by abhushanaj** [comment]
Okay Sir. I'll make the changes you asked.
Regarding the vnenv is because I am using my old system on which all the probelms were generated as discussed with you. 

Launching everything in an virtual environment for me finally led to working of the system again, which contains few system files which are not a part of the codebase. So i have added that to gitgnore

**Comment by tanishq9** [comment]
Ok, got it, thanks for clarifying.

**Comment by abhushanaj** [comment]
@tanishq9 Sir, I have made the changes you mentioned. You can review it again thank you!

**Pull request merged**
