### PR TITLE
Label image python script.

### LINKED ISSUE #71: add label_image.py script which was made/issue in data modeling repo. [Python+Tensorflow]
this label_image.py script is used to predict the leaf image's label

### PR DESCRIPTION
**Pull request by AdityaSingh17**
Fixes #71 
Files added: label_images.py

### CODE REVIEW

**Comment by AdityaSingh17** [comment]
I have taken the liberty to add the prediction function as well (which happens to be assigned to me and is currently open as a PR in Data modeling repository  [here](https://github.com/CropAi/Data-Modeling/pull/80).)

**Review by tanishq9 — COMMENTED** [review]
We don't have encoder.pkl in backend repository, also, gdd will download the h5 model and store it in our backend, so we could have simply added the model file here in backend rather than using google drive downloader. Moreover, we are discussing to deploy the model separately from backend because that can help us manage updates and performance in a better way.

**Comment by AdityaSingh17** [comment]
@tanishq9 So what I will do is delete function to download the model, and add the model file along with encoder.pkl file directly.
By the way, everything else working fine?
Any changes you suggest that I must make?

**Comment by tanishq9** [comment]
> So what I will do is delete function to download the model, and add the model file along with encoder.pkl file directly.
> By the way, everything else working fine?

Yes, the script will give the right output. But we prefer deploying our model now, rather than doing everything in the same API. If you want to deploy this model, then we will create a new issue for it.

**Comment by AdityaSingh17** [comment]
@tanishq9 What exactly do I have to do?

**Comment by tanishq9** [comment]
> @tanishq9 What exactly do I have to do?

You have experience in deploying such type of models ?

**Comment by AdityaSingh17** [comment]
@tanishq9 I dont think I understand you properly. Can we have a chat on slack?

**Comment by tanishq9** [comment]
Sure.

**Pull request closed without merging**
