### PR TITLE
File successfully uploaded

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Issue #85 
Added the image in screenshots_folder

### CODE REVIEW

**Review by tanishq9 — COMMENTED** [review]
This is not what you are supposed to do, did you read the issue clearly ?

**Comment by shreyakapoor08** [comment]
@tanishq9 yes I read it. Can you please help me with where I went wrong?

**Comment by tanishq9** [comment]
what you have uploaded is picture of a leaf, is that what the issue was ?

**Comment by shreyakapoor08** [comment]
@tanishq9 
Got it. I am sorry. I thought we have to add the uploaded image in the folder. 
I will correct it

**Comment by tanishq9** [comment]
Yes, read the issue clearly. I have properly explained everything.

**Comment by shreyakapoor08** [comment]
@tanishq9 Kindly check :)

**Comment by tanishq9** [comment]
No, the screenshot has to be the image of backend log which show the output, not a picture of lead which you uploaded.

**Comment by tanishq9** [comment]
Test it on an image from the dataset that we are using and not on any random image, rest all is fine. I am merging this PR, I will remove that extra image myself. Well done !

**Comment by shreyakapoor08** [comment]
@tanishq9 Thank you☺
I have also done it the way you said. and raised a PR for it. You can check that.

**Pull request merged**
