### PR TITLE
Added result as json

### LINKED ISSUE #87: Refactor 'file_upload' route code to send the JSON according to the predicted category
Example if the output from python script is : 'Pepper__bell___Bacterial_spot', then use `data.js` to send the appropriate JSON as response.

### PR DESCRIPTION
**Pull request by abhushanaj**
closes #87 
@tanishq9 Sir, kindly let me know if changes are needed. Thank you!!

**Screenshot for Tomato Septoria Leaf which I have:**
Screenshot (126)

### CODE REVIEW

**Review by tanishq9 — COMMENTED** [review]
Isn't it result[2] that contain the predicted label, you are using result[0] ? did you comment out some lines in `label_image.py` ?
PS : Whatever you print out in the python script will be part of your response from the python script.

**Comment by tanishq9** [comment]
Also, in case of error from this route, which you can try it uploading pdf in place of image, the server crashes, instead of that, check that uploaded file is only image (.png/.jpeg/.jpg)

**Comment by abhushanaj** [comment]
> Also, in case of error from this route, which you can try it uploading pdf in place of image, the server crashes, instead of that, check that uploaded file is only image (.png/.jpeg/.jpg)

Okay I will give the condition for only images then ! I'll make this change!

**Comment by abhushanaj** [comment]
> atever you print out in the python script will be part of your response from th

Yes that is correct Sir! I have commented the parts for print model parts! Do I uncomment them since they are not really the answers to problem
Do I keep it as result [2] only??

**Comment by abhu-A-J** [comment]
> > atever you print out in the python script will be part of your response from th
> 
> Yes that is correct Sir! I have commented the parts for print model parts! Do I uncomment them since they are not really the answers to problem
> Do I keep it as result [2] only??

**Comment by abhushanaj** [comment]
@tanishq9 Sir, I have added file type check for an image in two places  (if image not entered, then python script won't run but result in an JSON with an error message). I have also corrected the return result to result[2] and I have uncommented the lines as well in my repo so no further confusion is present!

**Comment by tanishq9** [comment]
No, result[0] is fine, actually the commented lines were not reflecting in files changed and I wanted to just ensure that you know what you were doing. Let me review your image checker now.

**Comment by abhushanaj** [comment]
> No, result[0] is fine, actually the commented lines were not reflecting in files changed and I wanted to just ensure that you know what you were doing. Let me review your image checker now.

Okay! I have changed it back to result[0]. Sir you can review it now! Thanks!

**Review by tanishq9 — COMMENTED** [review]
Empty JSON response, although the backend logs are being printed.

Screenshot (289)

**Comment by abhushanaj** [comment]
@tanishq9 Sir, made the changes to data.js file as required!

**Comment by tanishq9** [comment]
@abhu-A-J I am still getting an empty response.

**Comment by abhushanaj** [comment]
@tanishq9 Sir, here's what I am getting:

- On incorrect input (Eg: pdf)
Screenshot (128)

- On correct input (image)
Screenshot (129)

**Comment by tanishq9** [comment]
Well done @abhu-A-J

**Comment by abhushanaj** [comment]
> Well done @abhu-A-J

Thank you Sir! :)

**Pull request merged**
