### PR TITLE
add_image_feature

### PR DESCRIPTION
**Pull request by abhishekgupta368**
show the leaf image selected by a user below the file upload form. [HTML+CSS] #68

file added:
-> modified Index.html

feature implemented:
-> show uploaded an image on the screen.
Capture

### CODE REVIEW

**Comment by tanishq9** [comment]
Screenshot (254)
The form box should expand only when image is selected and not before that. Try to hide and show div image when the file is selected. Also, increase the height to 300 (go for height such that the screen doesnt have to scroll)

**Review by tanishq9 — COMMENTED** [review]
Screenshot (254)
The form box should expand only when image is selected and not before that. Try to hide and show image when the file is selected. Also, increase the height to 300 (go for such a height that the user doesnt has to scroll the screen)

**Review by tanishq9 — COMMENTED** [review]
The button should have been more below the file selector but I think its good to go for now. Merging it, you should also update your master branch before sending PR.

**Comment by abhishekgupta368** [comment]
I update evening only

**Pull request merged**
