### PR TITLE
 contribution guidlines

### PR DESCRIPTION
**Pull request by Adyasha8105**
Contribution Guidelines

### CODE REVIEW

**Comment by Adyasha8105** [comment]
@tanishq9  I was a little late :(.

**Comment by tanishq9** [comment]
You should also mention how the participant can update the master branch of their forked repo.

**Comment by Adyasha8105** [comment]
After making changes, will u merge it?

**Comment by tanishq9** [comment]
I will recommend you to add something new to the already existing contributing.md file. I see there are couple of things in your file which are not in the current file. I would be happy to merge if you could pull this off !

**Comment by Adyasha8105** [comment]
> I will recommend you to add something new to the already existing contributing.md file. I see there are couple of things in your file which are not in the current file. I would be happy to merge if you could pull this off !

ok then I will do it

**Comment by abhushanaj** [comment]
@tanishq9 Sir, I think the part which @Adyasha8105  added at the bottom is really informative and good where so many git commands are mentioned. I think we should that. 
Also @Adyasha8105 you can use .md syntax for commands for `git` and use `#` for heading!! You can use this [resource](https://www.markdownguide.org/)

**Comment by Adyasha8105** [comment]
@tanishq9 sir can you now check it?

**Comment by Adyasha8105** [comment]
> @tanishq9 Sir, I think the part which @Adyasha8105 added at the bottom is really informative and good where so many git commands are mentioned. I think we should that.
> Also @Adyasha8105 you can use .md syntax for commands for `git` and use `#` for heading!! You can use this [resource](https://www.markdownguide.org/)

Thanks, @abhu-A-J for your suggestion.

**Review by tanishq9 — APPROVED** [review]
Well done @Adyasha8105

**Comment by tanishq9** [comment]
Also, thanks for your valuable suggestions @abhu-A-J

**Pull request merged**
