### PR TITLE
Create Tomato_Target_Spot

### LINKED ISSUE #41: Make a text file for leaf disease "Tomato__Target_Spot"
You should make a text file for this leaf disease and add the symptoms, treatment and recommended products for this leaf disease in leaf disease data folder. 

**FORMAT OF TEXT FILE** 

Symptoms : (Write atleast 3 points)
----
Treatment : (Write atleast 2/3 points)
----
Recommended Products : (Give 2 or 3 links)
----

**EXAMPLE TEXT FILE WITH CORRECT FORMAT** 

Symptoms : 
1 : The lesions are dark brown and appear leathery with faint, concentric rings giving a target-spot effect.
2 : At first the spots are small (1 /8 inches in diameter) and oval or angular in shape, but later the spots can enlarge to about 1/2 inches.

Treatment :
1 : Plant only diseasefree, certified seed.
2 : Follow a complete and regular foliar fungicide spray program.                
3 : Allow tubers to mature before digging, dig when vines are dry, not wet, and avoid excessive wounding of potatoes during harvesting and handling.                         
                      
             
Recommended products :
1 : Harvest-Guard : https://www.planetnatural.com/product/floating-row-cover/
2 : AllDown : https://www.planetnatural.com/product/vinegar-weed-killer/

### PR DESCRIPTION
**Pull request by Sapna2001**
Fixes Issue#41

I have created the text file. Please review it.

### CODE REVIEW

**Comment by tanishq9** [comment]
The information is good, but please update your PR message, the issue should be a hyperlink.
Refer this : https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by Sapna2001** [comment]
Issue #41

**Comment by tanishq9** [comment]
No, you are linking PR to PR, link an issue to it.

**Comment by tanishq9** [comment]
Like this : #41

**Pull request merged**
