### PR TITLE
Formidable Package addition

### LINKED ISSUE #69: use formidable module for parsing form data, i.e file uploads, save this file in the backend and pass this as argument to dummy.py. [JS+PYTHON]
Refer this to know how to use formidable : https://www.npmjs.com/package/formidable

Also, the dummy.py script should return the first 5 characters of the file name, why ? Just to check whether we are able to correctly send the file path from the child process that we created in '/file_upload' route 

Make sure the image file is being saved in the backend, this image will be required by our python script later on.

### PR DESCRIPTION
**Pull request by abhushanaj**
fixes #69 

- Added npm package formidable to parse the incoming image, store it in current directory for the server, get the file details such as name and type and pass it to a child process and display it back on POST route endpoint
- The image is stored in main root directory in some encoded form

@tanishq9 Sir, you can review it and let me know about the changes if needed. Thanks!

### CODE REVIEW

**Review by tanishq9 — COMMENTED** [review]
I see the image file is getting saved on backend, but the images are not of .png/.jpg extension, please look into it.

**Comment by abhushanaj** [comment]
> I see the image file is getting saved on backend, but the images are not of .png/.jpg extension, please look into it.

Okay, I thought we needed in encoded form. I'll make the changes.
**Edit:** @tanishq9 Sir made the extension preserve on save. You can review again

**Review by tanishq9 — COMMENTED** [review]
Yes, works well. Now, tell me do you think will it be a good idea to put these saved images in the .gitignore ? Since, I don't want them to clutter the github project online.

**Comment by abhushanaj** [comment]
> Yes, works well. Now, tell me do you think will it be a good idea to put these saved images in the .gitignore ? Since, I don't want them to cluster the github project online.

Can't python developers write a script where it reads the picture, does the machine learning stuff and just before returning the result delete the image??
We can also keep the picture in same directory from where the script will read it and delete it after the work is done? 
Also, I don't think we can save the image directly to .gitignore right? Because we need a path to directory and .gitignore is a text file??

**Comment by tanishq9** [comment]
I meant we can create a folder, add all saved images there and then add that folder name in .gitignore.

**Comment by abhushanaj** [comment]
> I meant we can create a folder, add all saved images there and then add that folder name in .gitignore.

oh yeah we can do that! I misunderstood what you were saying! Makes sense now!

**Comment by tanishq9** [comment]
But yeah, playing with paths can get messy sometimes, lets leave that work to python developers for now. Will incorporate this thing in issue : https://github.com/CropAi/Backend/issues/71

**Comment by abhushanaj** [comment]
> But yeah, playing with paths can get messy sometimes, lets leave that work to python developers for now. Will incorporate this thing in issue : #71

Okay Sir, if it doesn't work .gitignore is always there for the rescue

**Comment by tanishq9** [comment]
> > But yeah, playing with paths can get messy sometimes, lets leave that work to python developers for now. Will incorporate this thing in issue : #71
> 
> Okay Sir, if it doesn't work .gitignore is always there for the rescue

Yes, because currently label_image.py script in data-modeling doesn't delete that processed image, so, I will add this issue there as well of modifying script.

**Pull request merged**
