### PR TITLE
add_potato_healthy

### PR DESCRIPTION
**Pull request by abhishekgupta368**
Make a text file for leaf disease "Potato___healthy" #44

file added:
-> potato_healthy

feature implemented:
-> information is added regarding the healthy potato

### CODE REVIEW

**Comment by Adyasha8105** [comment]
> Make a text file for leaf disease "Potato___healthy" #44
> 
> file added:
> -> potato_healthy
> 
> feature implemented:
> -> information is added regarding the healthy potato

this is about early blight.

**Comment by tanishq9** [comment]
@Adyasha8105 even i thought the same by looking at the first line of symptoms. Can you confirm if this is the case @abhishekgupta368 ?

**Comment by tanishq9** [comment]
Anyways, if it's not, it can be later deleted and issue can be reopened.

**Comment by abhishekgupta368** [comment]
some content and symptoms can be the same, you can't create the infection from yourself.

**Comment by abhishekgupta368** [comment]
@Adyasha8105 just specify where is the case of duplication.

**Pull request merged**
