### PR TITLE
Added disabling of button feature!

### LINKED ISSUE #91: Disable submit button till response is received from the backend (/file_upload API)
This is to prevent multiple requests being send to backend at once.

### PR DESCRIPTION
**Pull request by abhushanaj**
closes #91 

@tanishq9 Sir, the styling of the button might make it look it's not disabled! But to check it I have added a `console.log("Request from the client")` in post route so check it. It works!
We can click the submit button multiple times but the statement is printed only once. 
Kindly let me know if any changes are needed! Thank you!

### CODE REVIEW

**Review by tanishq9 — COMMENTED** [review]
Could you explain how setTimeout() is helping in this case and yes, its working, but you have not explained all changes that you did in code. Also, you can try to make cursor default or search for some CSS classes online which can make the button look 'disabled'.

**Comment by abhushanaj** [comment]
> Could you explain how setTimeout() is helping in this case and yes, its working, but you have not explained all changes that you did in code. Also, you can try to make cursor default or search for some CSS classes online which can make the button look 'disabled'.

I was having trouble when the button was disabled immediately! Sometimes the route was hit, but sometimes the button was getting disabled faster before even hitting the route! So I made it disabled after 1s itself! 

**Regarding css:** Do you think making it some color would create a impression? Maybe grey?? or red ?? Or maybe we'll add a text saying `Please wait....` instead of submit Sir?

**Comment by tanishq9** [comment]
you can show a loader on the screen and set its 'cancelable' to false, by 'cancelable' I mean it cannot be removed from window until we get the response. You can search for the exact property name as well and also try if you can get some better working solution for the button.

I don't recommend changing color, as on hovering the button will still look clickable and prefer showing a loader over some text like 'Please wait'.

**Comment by abhushanaj** [comment]
> you can show a loader on the screen and set its 'cancelable' to false, by 'calcelable' I mean it cannot be removed from window. You can search for the exact property name as well.

Okay Sir, I will try this and let you know about the progress! Thanks!

**Comment by tanishq9** [comment]
@abhu-A-J what is your update on this issue ?

**Comment by abhushanaj** [comment]
@tanishq9 Sir Made the changes!!

**Comment by tanishq9** [comment]
If I press 'ESC' key even once, the screen freezes and output json is not shown even though backend is showing the category in the logs.

Screenshot (291)

**Comment by abhushanaj** [comment]
> If I press 'ESC' key even once, the screen freezes and output json is not shown even though backend is showing the category in the logs.
> 
> Screenshot (291)

Made the changes Sir, Discussed the reasons and approach on slack! Thank you!

**Pull request merged**
